Add an audio dependency(Asteroid)
PyTorchLightning/lightning-flash pull request #573
Opened 2021-07-13 08:56 UTC by hihunjin

## What does this PR do?

Add an audio dependency(Asteroid)

Fixes # (issue)

## Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/lightning-flash/tree/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? [not needed for typos/docs]
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/lightning-flash/blob/master/CHANGELOG.md)?

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

We've discussed this pr on our slack channel.

## Did you have fun?
Make sure you had fun coding 😄

2021-07-13 09:09 UTC, Borda requested changes
we cannot add this dependency as it creates a cycle: Asteroid > PL > TM
moreover, the requested version is very resting PT versions
https://github.com/asteroid-team/asteroid/blob/ee1ff2447b5cceb6d0df006cb33e7fee9235ea23/requirements/torchhub.txt#L5

2021-07-13 09:13 UTC, hihunjin commented
> ignore me here... @hihunjin

What was TM and PT? PT=PyTorch version.
I guess you did a good mention. what if like
```sh
asteroid-filterbanks>=0.4.0
requests
filelock
SoundFile>=0.10.2
huggingface_hub>=0.0.2
```
on requirement?

2021-07-13 09:18 UTC, Borda commented
> I guess you did a good mention. what if like

no, it is fine, FLash requires PyTorch 1.8 as well as Asteroid
https://github.com/PyTorchLightning/lightning-flash/blob/f7a86eae45786db8ef56b8b24f3e28e13d2be581/requirements.txt#L1

2021-07-13 09:53 UTC, tchaton commented on flash/core/utilities/imports.py
> +_AUDIO_AVAILABLE = all([
Neat ! Good start :)

2021-07-13 10:34 UTC, ethanwharris approved these changes
Awesome, LGTM :smiley:

2021-07-14 07:30 UTC, tchaton approved these changes
LGTM !

2021-07-14 07:41 UTC, akihironitta approved these changes

2021-07-14 08:19 UTC, merged